# .github/workflows/deploy.yml

name: Deploy SvelteKit to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm install --force

      - name: Build SvelteKit application
        run: npm run build

      - name: Verify build directory contents # <-- 이 단계를 추가합니다!
        run: |
          ls -R ./build # build 폴더와 그 안의 내용물을 재귀적으로 모두 나열
          if [ -d "./build" ]; then # build 폴더가 존재하는지 확인
            echo "::notice::Build directory exists and contains files:"
            ls -al ./build
          else
            echo "::error::Build directory was NOT created!" # build 폴더가 없으면 에러 발생
            exit 1 # 워크플로우 실패
          fi

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
          publish_branch: gh-pages